const test=require('node:test'),assert=require('node:assert/strict'),C=require('../app/manuscript-core.js');
test('all upstream stages are covered without credentials or synthetic certainty',()=>{const v={protocol:{text:'Protocol',history:['old']},eligibility:{criteria:[{condition:'Adults'}]},search:{databases:['pubmed']},searchResults:{runs:[{query:'trial',apiKey:'secret'}]},screening:{full:{human:{a:{vote:'yes'}}},model:{token:'secret'}},fulltext:{records:[{uid:'a',title:'Trial',fullText:{pdf:'secret'}}]},extraction:{studies:{a:{done:true}},extractionFlow:{approved:true}},rob:{assess:{a:{overall:'low'}},token:'secret'},analysis:{rows:[{n:50}],runs:[{id:'r',engineSource:'arbitrary code',methods:'Methods'}]},coe:{real:{records:[{final_coe:'low'}]},synthetic:{records:['DO NOT INCLUDE']}}};const s=C.projectSources(v);assert.equal(s.length,10);const json=JSON.stringify(s);assert(!json.includes('secret'));assert(!json.includes('arbitrary code'));assert(!json.includes('DO NOT INCLUDE'));assert(json.includes('extractionFlow'));});
test('packet splitting retains all source characters',()=>{const sources=[{id:'S1',stage:'Test',data:{text:'x'.repeat(45000)}}];assert.equal(C.packets(sources).map(p=>p.text).join(''),JSON.stringify(sources[0].data,null,2));});
test('evidence digest must quote exact source',()=>{const p={id:'S1-1',text:'RR 0.8; 95% CI 0.6 to 1.1'};assert.throws(()=>C.facts({facts:[{quote:'RR 0.7'}],gaps:[]},p),/traced/);assert.equal(C.facts({facts:[{quote:'RR 0.8',note:'Reported estimate'}],gaps:[]},p).facts.length,1);});
test('draft sections require valid source references and unique IDs',()=>{assert.throws(()=>C.validate({sections:[{id:'methods',text:'text',sourceIds:['invented']}],issues:[]},['methods'],['S1-1']),/Invalid/);assert.throws(()=>C.validate({sections:[],issues:[]},['methods'],[]),/Invalid/);});
test('bibliography uses supplied metadata and deduplicates DOI',()=>{const r={uid:'a',title:'Trial',authors:['Smith'],year:'2020',doi:'10.1/example'};assert.equal(C.references({extraction:{records:[r]},fulltext:{records:[r]}}).length,1);assert.deepEqual(C.references({}),[]);});
test('export keeps section headings and custom user text',()=>{const x=C.wordItems('Title\nMy review\n\nMethods\nEdited methods.\nExtra detail.');assert.equal(x[0].label,'Title');assert.equal(x[1].label,'Methods');assert(x[1].definition.includes('Extra detail.'));});
test('internal source IDs stay in metadata rather than manuscript prose',()=>{const x=C.validate({sections:[{id:'methods',text:'Based on saved criteria. (sourceIds: S1-1)',sourceIds:['S1-1']}],issues:[]},['methods'],['S1-1']);assert.equal(x.sections[0].text,'Based on saved criteria.');assert.deepEqual(x.sections[0].sourceIds,['S1-1']);});
test('editorial corrections must match the existing draft',()=>{const rows=[{id:'results',text:'No studies exist.'}];assert.equal(C.correct(rows,{corrections:[{id:'results',find:'No studies exist.',replace:'Study results are not saved in this workspace.'}],issues:[]}).sections[0].text,'Study results are not saved in this workspace.');assert.equal(rows[0].text,'No studies exist.');assert.throws(()=>C.correct(rows,{corrections:[{id:'results',find:'invented text',replace:'x'}],issues:[]}),/traced/);});
