const test=require('node:test'),assert=require('node:assert/strict'),C=require('../app/protocol-core.js');
const source='Adults with fibromyalgia. Exclude animal studies. Randomized trials. Search PubMed and Cochrane Library. English only.';
const raw={question:'Exercise for fibromyalgia',reviewType:'Systematic Review',framework:'PICO',rows:[{title:'Population',inclusionQuotes:['Adults with fibromyalgia.'],exclusionQuotes:['Exclude animal studies.']},{title:'Study design',inclusionQuotes:['Randomized trials.'],exclusionQuotes:[]}],databases:['PubMed','Cochrane Library','Scopus'],searchQuotes:['Search PubMed and Cochrane Library.'],limitQuotes:['English only.'],issues:[]};
const mapping=C.validateHandoff(raw,source);
test('only traced rules and explicit databases pass',()=>{assert.equal(mapping.rows.length,2);assert.deepEqual(mapping.databases,['PubMed','Cochrane Library']);assert.throws(()=>C.validateHandoff({...raw,rows:[{...raw.rows[0],inclusionQuotes:['Adults aged 18 to 65.']}]},source),/traced/);});
test('new plans reset stale strategies and keep exact criteria',()=>{const result=C.prepare(mapping,{manualRefinement:{stale:true}},{queries:{pubmed:{text:'old'}},concepts:[{label:'unrelated'}]});assert.equal(result.eligibility.manualRefinement,null);assert.deepEqual(result.search.queries,{});assert.equal(result.search.criteriaSnapshot.rows[0].condition,result.eligibility.criteria[0].condition);assert.deepEqual(result.search.databases,['pubmed','cochrane']);});
function memory(){const data=new Map();return {getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};}
test('handoff is scoped and backs up previous work',()=>{const s=memory();s.setItem('aimstep-eligibility:p1','{"question":"old"}');s.setItem('aimstep-eligibility:p2','{"question":"other"}');C.commit(s,'p1',mapping,'synthetic');assert.equal(JSON.parse(s.getItem('aimstep-protocol-backups:p1'))[0].eligibility.question,'old');assert.equal(JSON.parse(s.getItem('aimstep-eligibility:p2')).question,'other');});
test('storage failure rolls back all handoff keys',()=>{const s=memory();s.setItem('aimstep-eligibility:p1','{"question":"old"}');const set=s.setItem;let fail=true;s.setItem=(k,v)=>{if(k==='aimstep-search-strategy:p1'&&fail){fail=false;throw Error('quota');}set(k,v)};assert.throws(()=>C.commit(s,'p1',mapping,'synthetic'),/restored/);assert.equal(s.getItem('aimstep-eligibility:p1'),'{"question":"old"}');assert.equal(s.getItem('aimstep-protocol-backups:p1'),null);});
test('draft requires every planned section exactly once',()=>{assert.throws(()=>C.validateDraft({sections:[],issues:[]}),/omitted/);assert.equal(C.validateDraft({sections:C.sections.map(([id])=>({id,text:'Not specified — to confirm'})),issues:[]}).sections.length,14);});
