/* Project-scoped Analysis: import → AI review → two confirmations → computation. */
(async function(){
'use strict';
const C=AimstepAnalysisCore,AI=AimstepAnalysisAI,O=AimstepAnalysisOutput,I=AimstepExtractionFormImport,R=AimstepExtractionResults;
const $=id=>document.getElementById(id),esc=O.esc,now=()=>new Date().toISOString(),uuid=()=>crypto.randomUUID();
const params=new URLSearchParams(location.search),projectId=params.get('projectId')||params.get('project')||'',scope=projectId||'default';
const link=(file,view)=>{const u=new URL(file,location.href);if(projectId)u.searchParams.set('projectId',projectId);if(view)u.searchParams.set('view',view);return u.href;};
for(const [selector,file,view] of [['[data-home]','index.html'],['[data-workflow]','index.html','project'],['[data-toolset]','index.html','toolset'],['[data-prev]','risk-of-bias.html'],['[data-next]','certainty-of-evidence.html']])document.querySelectorAll(selector).forEach(a=>a.href=link(file,view));
try{const p=JSON.parse(sessionStorage.getItem('aimstep-active-project'));if(p?.id===projectId&&p.name){$('project-name').textContent=p.name;$('project-name').href=link('index.html','project');$('project-name').hidden=false;}}catch(_){}
let ws,db,busy='',controller=null,worker=null,progress=0,saveChain=Promise.resolve(),saveFailed=false,view='results';
const defaults=()=>({version:2,rows:[],sources:[],requirements:'',requirementFiles:[],dataReview:null,dataConfirmed:null,plan:null,planReview:null,planConfirmed:null,runs:[],selectedRun:'',audit:[]});
function openDB(name){return new Promise((resolve,reject)=>{const r=indexedDB.open(name,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('projects'))r.result.createObjectStore('projects',{keyPath:'id'});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.onblocked=()=>reject(Error('Another tab is blocking project storage. Close it and reload.'));});}
function read(database){return new Promise((resolve,reject)=>{const r=database.transaction('projects').objectStore('projects').get(scope);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
function put(state){return new Promise((resolve,reject)=>{const tx=db.transaction('projects','readwrite');tx.objectStore('projects').put({id:scope,state,updatedAt:now()});tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||Error('Save aborted.'));});}
async function external(name){const store=await openDB(name);try{return await read(store);}finally{store.close();}}
function status(id,text){$(id).textContent=text;$(id).hidden=!text;}
function log(type,detail){ws.audit.push({at:now(),type,...detail});}
function persist(){const snapshot=structuredClone(ws);const task=saveChain.catch(()=>{}).then(()=>put(snapshot));saveChain=task;task.then(()=>{saveFailed=false;renderControls();},e=>{saveFailed=true;status('analysis-status','Could not save this project: '+e.message+'. Confirmation and analysis are disabled until saving succeeds.');renderControls();});return task;}
async function atomic(change){await saveChain;const before=structuredClone(ws);try{change();await put(structuredClone(ws));saveFailed=false;}catch(e){ws=before;throw e;}}
function setProgress(n,label){progress=Math.max(0,Math.min(100,Math.round(n)));const bar=$('analysis-progress');bar.style.setProperty('--progress',progress+'%');bar.querySelector('span').style.width=progress+'%';bar.querySelector('b').textContent=progress+'%';bar.setAttribute('aria-valuenow',String(progress));if(label!==undefined)status('analysis-status',label);}
function reveal(part){if($('toggle-'+part).getAttribute('aria-expanded')==='false')$('toggle-'+part).click();}
function bindCollapse(part){const key='aimstep-analysis-'+part+'-collapsed:'+scope,body=$(part+'-body'),button=$('toggle-'+part);const set=v=>{body.hidden=v;button.setAttribute('aria-expanded',String(!v));button.setAttribute('aria-label',(v?'Expand ':'Collapse ')+({data:'Data sources',requirements:'Analysis Requirements',results:'Analysis results'})[part]);};try{set(localStorage.getItem(key)==='1');}catch(_){}button.onclick=()=>{set(!body.hidden);try{localStorage.setItem(key,body.hidden?'1':'0');}catch(_){}};}
function issues(){return [...C.validate(ws.rows),...(ws.dataReview?.signature===C.dataSignature(ws)?ws.dataReview.issues:[])];}
function renderControls(){if(!ws)return;const dataOK=C.confirmedData(ws),planOK=C.confirmedPlan(ws),blocked=!!busy||saveFailed;
 for(const id of ['from-extraction','import-data','clear-data','add-data-row','import-requirements','clear-requirements'])$(id).disabled=blocked;
 $('check-data').disabled=blocked||!ws.rows.length;
 $('confirm-data').disabled=blocked||!ws.dataReview||ws.dataReview.signature!==C.dataSignature(ws)||issues().some(x=>x.severity==='error');
 $('review-requirements').disabled=blocked||!dataOK||!ws.requirements.trim();
 $('confirm-requirements').disabled=blocked||!dataOK||!ws.planReview||ws.planReview.input!==C.inputSignature(ws)||ws.planReview.signature!==C.signature(ws.plan)||C.planErrors(ws.plan,ws.rows,ws.requirements).length>0;
 $('start-analysis').disabled=blocked||!C.canRun(ws);
 $('export-analysis').disabled=blocked||!currentRun();$('clear-results').disabled=blocked||(!ws.runs.length&&!progress);
 $('stop-analysis').hidden=busy!=='analysis';$('stop-data').hidden=busy!=='data';$('stop-requirements').hidden=busy!=='requirements';
 $('data-confirmed').textContent=dataOK?'Confirmed':'';$('requirements-confirmed').textContent=planOK?'Confirmed':'';
 $('data-confirmed').classList.toggle('confirmed',dataOK);$('requirements-confirmed').classList.toggle('confirmed',planOK);
 $('requirements-input').disabled=!!busy;$('data-editor').inert=!!busy;$('plan-editor').inert=!!busy;
 if(!busy&&!currentRun()&&['','Check and confirm data, then review and confirm the analysis requirements.','Review and confirm the analysis requirements to enable Start.','Ready to start.'].includes($('analysis-status').textContent))status('analysis-status',dataOK?(planOK?'Ready to start.':'Review and confirm the analysis requirements to enable Start.'):'Check and confirm data, then review and confirm the analysis requirements.');
}
const labels={study:'Study ID',author:'Author',year:'Year',outcome:'Outcome',timepoint:'Time point',treat:'Treatment',type:'Type',n:'N',event:'Events',mean:'Mean',sd:'SD',unit:'Unit / scale',valueType:'Endpoint / change',design:'Design'};
function renderData(){
 $('source-list').innerHTML=ws.sources.map(s=>`<span>${esc(s.name)} · ${esc(s.at.slice(0,10))} <button class="btn small" type="button" data-remove-source="${esc(s.id)}" aria-label="Remove ${esc(s.name)}" ${busy?'disabled':''}>×</button></span>`).join('');
 $('data-editor').innerHTML=ws.rows.length?`<table><thead><tr><th>#</th>${C.fields.map(f=>`<th>${labels[f]}</th>`).join('')}<th></th></tr></thead><tbody>${ws.rows.map((r,i)=>`<tr><td>${i+1}</td>${C.fields.map(f=>`<td><input aria-label="Row ${i+1} ${labels[f]}" data-row="${i}" data-field="${f}" value="${esc(r[f])}" ${C.numeric.includes(f)?'inputmode="decimal"':''}></td>`).join('')}<td><button class="btn small" type="button" data-remove-row="${i}" aria-label="Remove row ${i+1}">×</button></td></tr>`).join('')}</tbody></table>`:'';
 renderDataFeedback();
}
function renderDataFeedback(){const current=ws.dataReview?.signature===C.dataSignature(ws),list=issues().filter(i=>i.code!=='empty-data');$('data-feedback').innerHTML=(current?ws.dataReview.feedback.map(t=>'<p>'+esc(t)+'</p>').join(''):'')+(list.length?'<ul>'+list.map(i=>`<li class="${i.severity==='error'?'error':''}">${i.row?'Row '+i.row+': ':''}${esc(i.message)}</li>`).join('')+'</ul>':'')+(ws.sources.flatMap(s=>s.notes||[]).map(n=>'<p>'+esc(n)+'</p>').join(''));
}
function options(values,selected){return values.map(v=>`<option value="${esc(v)}" ${String(selected)===String(v)?'selected':''}>${esc(v)}</option>`).join('');}
function renderPlan(){
 const p=ws.plan;if(!p){$('plan-editor').innerHTML='';return;}const sets=C.datasets(ws.rows);
 const cards=p.analyses.map((a,i)=>{const d=sets.find(d=>d.id===a.datasetId);if(!d)return `<p>Dataset ${esc(a.datasetId)} is no longer available. Review requirements again.</p>`;const select=(key,title,vals)=>`<label>${title}<select data-plan="${i}" data-setting="${key}">${options(vals,a[key])}</select></label>`,input=(key,title)=>`<label>${title}<input data-plan="${i}" data-setting="${key}" value="${esc(a[key])}" inputmode="decimal"></label>`;
 return `<div class="plan-card"><h3>${esc(d.name)} · ${esc(d.timepoint)}</h3><div class="plan-grid">${select('method','Analysis',['descriptive','frequentist','bayesian','both'])}${select('measure','Effect measure',d.type==='binary'?['RR','OR']:['MD','SMD'])}${select('reference','Reference treatment',[...new Set(d.rows.map(r=>r.treat))])}${select('model','Model',['random','common'])}<label>Better outcome<select data-plan="${i}" data-setting="smallBetter"><option value="false" ${!a.smallBetter?'selected':''}>Higher values</option><option value="true" ${a.smallBetter?'selected':''}>Lower values</option></select></label>${['bayesian','both'].includes(a.method)?select('prior','Heterogeneity prior',['halfnormal','uniform'])+input(a.prior==='uniform'?'priorMax':'priorScale',a.prior==='uniform'?'Prior upper limit':'Prior scale')+input('draws','Posterior draws')+input('seed','Random seed'):''}</div><label class="label">Rationale</label><textarea class="textarea" data-plan="${i}" data-setting="rationale">${esc(a.rationale||'')}</textarea></div>`;}).join('');
 $('plan-editor').innerHTML='<label class="label" for="plan-summary">Organised analysis plan</label><textarea class="textarea plan-summary" id="plan-summary">'+esc(p.summary)+'</textarea>'+(p.suggestions.length?'<div class="feedback"><b>Suggestions</b><ul>'+p.suggestions.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul></div>':'')+(p.excludedDatasets?.length?'<div class="feedback"><b>Excluded datasets</b><ul>'+p.excludedDatasets.map(e=>'<li>'+esc(e.datasetId+': '+e.reason)+'</li>').join('')+'</ul></div>':'')+cards+'<div id="plan-errors" class="feedback"></div>';
 renderPlanErrors();
}
function renderPlanErrors(){const el=$('plan-errors');if(!el)return;const errors=C.planErrors(ws.plan,ws.rows,ws.requirements);el.innerHTML=errors.length?'<ul>'+errors.map(e=>'<li class="error">'+esc(e)+'</li>').join('')+'</ul>':'';}
function currentRun(){return ws.runs.find(r=>r.id===ws.selectedRun)||ws.runs.at(-1);}
function renderResults(){const run=currentRun();$('run-picker').hidden=!run;$('result-tabs').hidden=!run;$('stale-note').hidden=!run||run.signature===C.planSignature(ws);if(!run){$('result-view').innerHTML='';$('saved-runs').innerHTML='';return;}
 $('saved-runs').innerHTML=ws.runs.map(r=>`<option value="${r.id}" ${r.id===run.id?'selected':''}>${esc(r.at.replace('T',' ').slice(0,19))} · ${r.results.length} analyses</option>`).join('');
 document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view)));
 $('result-view').innerHTML=view==='results'?O.body(run):'<div class="document">'+esc(view==='methods'?run.methods:run.interpretation)+'</div>';
}
function render(){renderData();renderPlan();renderResults();renderControls();}
function changedData(){C.invalidate(ws);persist().catch(()=>{});renderDataFeedback();renderControls();renderResults();}
async function task(kind,fn){if(busy)return;busy=kind;controller=new AbortController();renderControls();try{await saveChain;await fn(controller.signal);}catch(e){if(controller.signal.aborted)status(kind==='data'?'data-status':kind==='requirements'?'requirements-status':'analysis-status','Stopped. Saved data and earlier results are kept.');else status(kind==='data'?'data-status':kind==='requirements'?'requirements-status':'analysis-status',e.message);}finally{busy='';controller=null;render();}}
async function reviewData(signal){reveal('data');const sig=C.dataSignature(ws);status('data-status','AI checking data…');await atomic(()=>{C.invalidate(ws);});renderControls();const response=await AI.check(ws.rows,signal,(i,n)=>status('data-status',i===n?'Saving data review…':'AI checking data '+Math.min(i+35,n)+' / '+n+' rows…'));if(signal.aborted)return;if(sig!==C.dataSignature(ws))throw Error('Data changed during review. Check again.');await atomic(()=>{ws.dataReview={...response,signature:sig,at:now()};log('data-reviewed',{model:response.model});});status('data-status',issues().some(x=>x.severity==='error')?'Resolve the listed errors, then check data again.':'Review the data and feedback, then click Confirm data.');}
async function importData(files,signal){reveal('data');let imported=0;const errors=[];for(const file of files){if(signal.aborted)return;try{status('data-status','Reading '+file.name+'…');const text=await I.sourceText(file),rows=C.parse(text,file.name.split('.').pop().toLowerCase(),file.name,I.csv);if(!rows.length)throw Error('No arm-level rows found. Use Study, Treatment, Outcome, Time point, N, and Events or Mean/SD columns.');if(rows.length+ws.rows.length>10000)throw Error('Import up to 10,000 arm-level rows per project.');const id=uuid();await atomic(()=>{ws.sources.push({id,name:file.name,kind:'local',at:now(),raw:text,snapshot:text,notes:[]});ws.rows.push(...rows.map(r=>({...r,sourceId:id})));C.invalidate(ws);log('data-imported',{name:file.name,rows:rows.length});});imported+=rows.length;}catch(e){errors.push(file.name+': '+e.message);}}
 renderData();if(imported)await reviewData(signal);if(errors.length)status('data-status',errors.join('\n')+(imported?' Imported rows were retained.':''));}
async function fromExtraction(signal){const data=(await external('aimstep-extraction'))?.state;if(!data)throw Error('No Extraction workspace was found for this project. Complete Extraction or import data from local.');const intake=C.extraction(data,R);if(!intake.rows.length)throw Error('No numerical outcome results were found in this project’s Extraction workspace. Add outcome data in Extraction or import a local table.');const existing=ws.sources.find(s=>s.kind==='extraction');if(existing&&!confirm('Replace the existing Extraction snapshot with the current results? Related confirmations will be reset.'))return;const id=existing?.id||uuid(),snapshot=C.signature(intake);await atomic(()=>{ws.rows=ws.rows.filter(r=>r.sourceId!==id);ws.sources=ws.sources.filter(s=>s.id!==id);ws.sources.push({id,name:'Extraction',kind:'extraction',at:now(),snapshot,notes:intake.notes});ws.rows.push(...intake.rows.map(r=>({...r,sourceId:id})));C.invalidate(ws);log('extraction-imported',{rows:intake.rows.length});});renderData();await reviewData(signal);}
async function checkUpstream(){const source=ws.sources.find(s=>s.kind==='extraction');if(!source)return true;const data=(await external('aimstep-extraction'))?.state;const snapshot=C.signature(C.extraction(data,R));if(snapshot===source.snapshot)return true;await atomic(()=>{C.invalidate(ws);log('extraction-source-changed',{});});status('data-status','Extraction results have changed. Click From Extraction, review the updated data and confirm again.');render();return false;}
async function reviewRequirements(signal){if(!C.confirmedData(ws))throw Error('Confirm the current data first.');if(!ws.requirements.trim())throw Error('Enter or import analysis requirements.');reveal('requirements');const input=C.inputSignature(ws);status('requirements-status','AI organising the requirements and checking the analysis plan…');await atomic(()=>{ws.planReview=null;ws.planConfirmed=null;});const result=await AI.plan(ws,signal);if(signal.aborted)return;if(input!==C.inputSignature(ws))throw Error('Requirements changed during review. Review again.');await atomic(()=>{ws.plan=result.plan;ws.planReview={input,signature:C.signature(ws.plan),at:now(),model:result.model};log('requirements-reviewed',{model:result.model});});status('requirements-status','Review the organised plan and suggestions. Edit settings if needed, then confirm.');}
function compute(state,signal){return new Promise((resolve,reject)=>{worker=new Worker('app/analysis-worker.js?v=1');const stop=()=>{worker?.terminate();worker=null;reject(new DOMException('Stopped','AbortError'));};signal.addEventListener('abort',stop,{once:true});const done=()=>{signal.removeEventListener('abort',stop);worker?.terminate();worker=null;};worker.onmessage=e=>{const m=e.data;if(m.type==='progress')setProgress(m.value,m.label);else if(m.type==='done'){done();resolve(m.results);}else{done();reject(Error(m.message));}};worker.onerror=e=>{done();reject(Error(e.message||'Analysis worker failed.'));};worker.postMessage({state});});}
async function start(signal){if(!C.canRun(ws))throw Error('Confirm the current data and analysis requirements before starting.');if(!await checkUpstream())throw Error('Extraction changed. Recheck and confirm data before analysis.');reveal('results');setProgress(5,'Validating the confirmed plan…');const snapshot=structuredClone(ws),sig=C.planSignature(ws);const engineResponse=await fetch('app/analysis-engine.js?v=1',{signal});if(!engineResponse.ok)throw Error('Could not load the numerical engine for this run.');const engineSource=await engineResponse.text();const results=await compute(snapshot,signal);if(signal.aborted)return;setProgress(90,'Preparing figures, interpretation and methods…');const run={id:uuid(),version:C.VERSION,engineSource,at:now(),signature:sig,results,data:snapshot.rows,sources:snapshot.sources,dataReview:snapshot.dataReview,dataConfirmed:snapshot.dataConfirmed,requirements:snapshot.requirements,plan:snapshot.plan,planReview:snapshot.planReview,planConfirmed:snapshot.planConfirmed,audit:snapshot.audit};run.methods=O.methods(run);run.interpretation=results.map(O.interpretation).join('\n\n──────────\n\n');
 if(signal.aborted)return;await atomic(()=>{ws.runs.push(run);ws.selectedRun=run.id;log('analysis-completed',{runId:run.id,version:C.VERSION});});setProgress(100,'Completed. Results, figures, interpretation and methods are ready.');}
function download(name,mime,body){const url=URL.createObjectURL(new Blob([body],{type:mime})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
async function exportRun(){const run=currentRun();if(!run||busy)return;busy='export';renderControls();try{
 let engine=run.engineSource;if(!engine){const response=await fetch('app/analysis-engine.js?v=1');if(!response.ok)throw Error('Could not load the reproducible engine. Retry Export.');engine=await response.text();}
 const files=[{name:'results.html',content:O.html(run)},{name:'results.json',content:JSON.stringify(run,null,2)},{name:'confirmed-plan.json',content:JSON.stringify({requirements:run.requirements,plan:run.plan,dataConfirmation:run.dataConfirmed,requirementsConfirmation:run.planConfirmed},null,2)},{name:'working-data.csv',content:C.csv([C.fields,...run.data.map(r=>C.fields.map(f=>r[f]))])},{name:'interpretation.docx',content:O.docx('Analysis interpretation',run.interpretation)},{name:'methods.docx',content:O.docx('Analysis methods',run.methods)},{name:'interpretation.txt',content:run.interpretation},{name:'methods.txt',content:run.methods},{name:'audit.json',content:JSON.stringify({dataReview:run.dataReview,planReview:run.planReview,sources:run.sources,events:run.audit},null,2)},{name:'engine.cjs',content:engine}];
 const effectRows=[['Outcome','Time point','Comparison','Method','Measure','Estimate','Lower 95%','Upper 95%']];for(const [i,r]of run.results.entries()){files.push({name:'figures/network-'+(i+1)+'.svg',content:O.network(r)});if(O.forest(r))files.push({name:'figures/forest-'+(i+1)+'.svg',content:O.forest(r)});for(const e of O.effects(r))effectRows.push([r.dataset.name,r.dataset.timepoint,e.treatment+' vs '+e.reference,e.method,r.plan.measure,e.estimate,e.lower,e.upper]);}
 files.push({name:'results.xlsx',content:R.workbook([{name:'Effects',rows:effectRows},{name:'Working data',rows:[C.fields,...run.data.map(r=>C.fields.map(f=>r[f]))]},{name:'Analysis plan',rows:[['Outcome','Time point','Method','Measure','Model','Reference','Rationale'],...run.results.map(r=>[r.dataset.name,r.dataset.timepoint,r.plan.method,r.plan.measure,r.plan.model,r.plan.reference,r.plan.rationale])]}])});
 files.push({name:'reproduce.cjs',content:`const fs=require('node:fs'),assert=require('node:assert/strict'),E=require('./engine.cjs'),run=JSON.parse(fs.readFileSync('results.json','utf8'));\nfor(const r of run.results){const p=r.plan,o={measure:p.measure,reference:p.reference,model:p.model,smallBetter:p.smallBetter};if(r.fr)assert.deepEqual(JSON.parse(JSON.stringify(E.frequentist(r.dataset.rows,o))),r.fr);if(r.by)assert.deepEqual(JSON.parse(JSON.stringify(E.bayesian(r.dataset.rows,{...o,prior:p.prior==='uniform'?{type:p.prior,max:p.priorMax}:{type:p.prior,scale:p.priorScale},draws:p.draws,seed:p.seed}))),r.by);}console.log('Reproduced numerical outputs match saved results.');\n`});
 download('aimstep-analysis-'+run.at.slice(0,10)+'-'+run.id.slice(0,8)+'.zip','application/zip',O.zip(files));
 }catch(e){status('analysis-status','Export failed: '+e.message);}finally{busy='';renderControls();}}
function bind(){
 ['data','requirements','results'].forEach(bindCollapse);
 $('from-extraction').onclick=()=>task('data',fromExtraction);
 $('import-data').onclick=()=>$('data-files').click();$('data-files').onchange=e=>{const files=[...e.target.files];e.target.value='';if(files.length)task('data',signal=>importData(files,signal));};
 $('check-data').onclick=()=>task('data',reviewData);
 $('confirm-data').onclick=()=>task('data',async()=>{if(!ws.dataReview||ws.dataReview.signature!==C.dataSignature(ws)||issues().some(i=>i.severity==='error'))throw Error('Complete the data check and resolve errors first.');if(!await checkUpstream())return;await atomic(()=>{ws.dataConfirmed={signature:C.dataSignature(ws),at:now()};log('data-confirmed',{});});status('data-status','Data confirmed.');});
 $('clear-data').onclick=()=>{if(busy||!confirm('Clear the working data and reset confirmations? Saved analysis runs will be retained.'))return;task('data',async()=>{await atomic(()=>{ws.rows=[];ws.sources=[];C.invalidate(ws);log('data-cleared',{});});status('data-status','');});};
 $('add-data-row').onclick=()=>{ws.rows.push({...C.canonical({}),sourceId:'manual'});changedData();renderData();};
 $('data-editor').addEventListener('input',e=>{const {row,field}=e.target.dataset;if(row===undefined||!field||busy)return;ws.rows[Number(row)][field]=e.target.value;changedData();});
 $('data-editor').addEventListener('click',e=>{const b=e.target.closest('[data-remove-row]');if(!b||busy)return;ws.rows.splice(Number(b.dataset.removeRow),1);changedData();renderData();});
 $('source-list').onclick=e=>{const b=e.target.closest('[data-remove-source]');if(!b||busy||!confirm('Remove this data source and its working rows? Confirmations will be reset.'))return;const id=b.dataset.removeSource;ws.rows=ws.rows.filter(r=>r.sourceId!==id);ws.sources=ws.sources.filter(s=>s.id!==id);changedData();renderData();};
 $('requirements-input').oninput=e=>{ws.requirements=e.target.value;C.invalidate(ws,'requirements');persist().catch(()=>{});renderControls();renderResults();};
 $('import-requirements').onclick=()=>$('requirements-files').click();$('requirements-files').onchange=e=>{const files=[...e.target.files];e.target.value='';if(!files.length)return;task('requirements',async signal=>{for(const f of files){if(signal.aborted)return;status('requirements-status','Reading '+f.name+'…');const text=/\.pdf$/i.test(f.name)?(await AimstepExtractionSources.readPdf(f)).doc.fullText:await I.sourceText(f);if(!text.trim())throw Error(f.name+': no readable requirements.');await atomic(()=>{ws.requirementFiles.push({name:f.name,text,at:now()});ws.requirements+=(ws.requirements?'\n\n':'')+text;C.invalidate(ws,'requirements');});}$('requirements-input').value=ws.requirements;if(C.confirmedData(ws))await reviewRequirements(signal);else status('requirements-status','Requirements imported. Confirm the data, then click Review requirements.');});};
 $('clear-requirements').onclick=()=>{if(busy||!confirm('Clear the analysis requirements and their confirmation? Saved runs will be retained.'))return;task('requirements',async()=>{await atomic(()=>{ws.requirements='';ws.requirementFiles=[];ws.plan=null;C.invalidate(ws,'requirements');log('requirements-cleared',{});});$('requirements-input').value='';status('requirements-status','');});};
 $('review-requirements').onclick=()=>task('requirements',reviewRequirements);
 $('confirm-requirements').onclick=()=>task('requirements',async()=>{if(!C.confirmedData(ws)||ws.planReview?.input!==C.inputSignature(ws)||C.planErrors(ws.plan,ws.rows,ws.requirements).length)throw Error('Review the requirements and resolve plan issues first.');await atomic(()=>{ws.planReview.signature=C.signature(ws.plan);ws.planConfirmed={signature:C.planSignature(ws),at:now()};log('requirements-confirmed',{});});status('requirements-status','Requirements confirmed. Start is now available.');});
 $('plan-editor').addEventListener('input',e=>{if(busy)return;if(e.target.id==='plan-summary')ws.plan.summary=e.target.value;else{const {plan,setting}=e.target.dataset;if(plan===undefined||!setting)return;let v=e.target.value;if(['priorScale','priorMax','draws','seed'].includes(setting))v=Number(v);if(setting==='smallBetter')v=v==='true';ws.plan.analyses[Number(plan)][setting]=v;}ws.planConfirmed=null;if(ws.planReview)ws.planReview.signature=C.signature(ws.plan);log('plan-edited',{});persist().catch(()=>{});renderPlanErrors();renderControls();renderResults();});
 $('plan-editor').addEventListener('change',e=>{if(['method','prior'].includes(e.target.dataset.setting))renderPlan();});
 for(const id of ['stop-data','stop-requirements','stop-analysis'])$(id).onclick=()=>controller?.abort();
 $('start-analysis').onclick=()=>task('analysis',start);$('export-analysis').onclick=exportRun;
 $('clear-results').onclick=()=>{if(busy||!confirm('Clear all saved analysis results, figures, interpretation and methods in this project? Confirmed data and analysis requirements will be kept.'))return;task('results-clear',async()=>{await atomic(()=>{log('analysis-results-cleared',{runIds:ws.runs.map(r=>r.id)});ws.runs=[];ws.selectedRun='';});view='results';setProgress(0,'');});};
 $('saved-runs').onchange=e=>{ws.selectedRun=e.target.value;persist().catch(()=>{});renderResults();};
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;renderResults();});
}
try{
 db=await openDB('aimstep-analysis');ws=Object.assign(defaults(),(await read(db))?.state||{});
 // Migrate legacy local imports as unconfirmed data; preserve the original store.
 if(!ws.rows.length&&!ws.sources.length&&!ws.audit.length){let legacy;try{legacy=JSON.parse(localStorage.getItem('aimstep-analysis:'+scope)||'null');}catch(_){}if(legacy?.imported?.length){const id=uuid();for(const o of legacy.imported)ws.rows.push(...o.rows.map(r=>({...C.canonical(r,{outcome:o.name,timepoint:o.timepoint,type:o.type}),sourceId:id})));ws.sources.push({id,name:'Previous Analysis imports',kind:'legacy',at:now(),snapshot:JSON.stringify(legacy.imported),notes:['Imported from the previous Analysis page. Review and confirm before running.']});await put(ws);}}
 $('requirements-input').value=ws.requirements;bind();render();if(currentRun())setProgress(100,'Saved analysis loaded.');document.body.dataset.ready='true';
}catch(e){status('analysis-status','Could not load the Analysis workspace: '+e.message);document.querySelectorAll('button').forEach(b=>b.disabled=true);}
})();
