/* Deterministic figures, interpretation, methods and portable export bundle. */
(function(root){
'use strict';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=x=>Number.isFinite(x)?Number(x.toPrecision(5)).toString():'Not estimable';
const ratio=m=>['RR','OR'].includes(m),scale=(m,x)=>ratio(m)?Math.exp(x):x;
function effects(r){const a=r.fr||r.by;if(!a)return [];return a.treats.slice(1).flatMap((t,i)=>{
 const out=[];if(r.fr){const x=r.fr.league[0][i+1];out.push({treatment:t,reference:a.reference,method:'Frequentist',estimate:scale(r.plan.measure,x.est),lower:scale(r.plan.measure,x.est-1.959963984540054*x.se),upper:scale(r.plan.measure,x.est+1.959963984540054*x.se),logEstimate:x.est,logLower:x.est-1.959963984540054*x.se,logUpper:x.est+1.959963984540054*x.se});}
 if(r.by){const x=r.by.league[0][i+1];out.push({treatment:t,reference:a.reference,method:'Bayesian',estimate:scale(r.plan.measure,x.median),lower:scale(r.plan.measure,x.lo),upper:scale(r.plan.measure,x.hi),logEstimate:x.median,logLower:x.lo,logUpper:x.hi});}return out;});}
const svgStyle='<style>text{font-family:Arial,sans-serif;font-size:12px;fill:#35303c}line{stroke:#79548e;stroke-width:2}circle{fill:#79548e}.bayes{stroke:#4569a1;fill:#4569a1}.axis{stroke:#aaa;stroke-width:1}.null{stroke:#aaa;stroke-dasharray:4 4}</style>';
function network(r){const rows=r.dataset.rows,T=[...new Set(rows.map(r=>r.treat))],W=800,H=410,R=135,pos=new Map(T.map((t,i)=>[t,[W/2+R*Math.cos(2*Math.PI*i/T.length-Math.PI/2),H/2+R*Math.sin(2*Math.PI*i/T.length-Math.PI/2)]])),by=new Map(),edges=new Map();for(const row of rows){if(!by.has(row.study))by.set(row.study,[]);by.get(row.study).push(row.treat);}for(const arms of by.values())for(let i=0;i<arms.length;i++)for(let j=i+1;j<arms.length;j++){const k=JSON.stringify([arms[i],arms[j]].sort());edges.set(k,(edges.get(k)||0)+1);}
 const lines=[...edges].map(([k,n])=>{const [a,b]=JSON.parse(k),[x,y]=pos.get(a),[u,v]=pos.get(b);return `<line x1="${x}" y1="${y}" x2="${u}" y2="${v}" style="stroke-width:${1+Math.sqrt(n)}"><title>${esc(a)} vs ${esc(b)}: ${n} studies</title></line>`;}).join('');
 const nodes=T.map(t=>{const [x,y]=pos.get(t),n=rows.filter(r=>r.treat===t).reduce((n,r)=>n+r.n,0);return `<circle cx="${x}" cy="${y}" r="${Math.min(22,5+Math.sqrt(n)/4)}"><title>${esc(t)}: ${n} participants</title></circle><text x="${x}" y="${y+(y<H/2?-29:34)}" text-anchor="middle">${esc(t.length>45?t.slice(0,42)+'…':t)}</text>`;}).join('');
 return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" role="img" aria-label="Treatment network">${svgStyle}${lines}${nodes}</svg>`;
}
function forest(r){const rows=effects(r);if(!rows.length)return '';const W=1100,L=250,R=370,H=70+rows.length*34;let lo=Math.min(0,...rows.map(x=>x.logLower)),hi=Math.max(0,...rows.map(x=>x.logUpper));const pad=(hi-lo)*0.1||1;lo-=pad;hi+=pad;const x=v=>L+(v-lo)/(hi-lo)*(W-L-R),ticks=Array.from({length:5},(_,i)=>lo+(hi-lo)*i/4);
 return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" role="img" aria-label="Forest plot">${svgStyle}<line class="null" x1="${x(0)}" x2="${x(0)}" y1="25" y2="${H-30}"/><text x="${L}" y="16">${esc(r.plan.measure)} · treatment versus ${esc(rows[0].reference)}${ratio(r.plan.measure)?' (log axis)':''}</text>${rows.map((r,i)=>{const y=40+i*34,c=r.method==='Bayesian'?'bayes':'';return `<text x="10" y="${y+4}">${esc(r.treatment.slice(0,34))}</text><line class="${c}" x1="${x(r.logLower)}" x2="${x(r.logUpper)}" y1="${y}" y2="${y}"/><circle class="${c}" cx="${x(r.logEstimate)}" cy="${y}" r="4"/><text x="${W-R+15}" y="${y+4}">${num(r.estimate)} (${num(r.lower)} to ${num(r.upper)}) · ${r.method}</text>`;}).join('')}${ticks.map(t=>`<text x="${x(t)}" y="${H-7}" text-anchor="middle">${num(scale(r.plan.measure,t))}</text>`).join('')}</svg>`;
}
function league(r,which){const fit=r[which];if(!fit)return '';return `<div class="table-wrap"><table><caption>${which==='fr'?'Frequentist 95% confidence':'Bayesian 95% credible'} intervals: row treatment versus column treatment</caption><thead><tr><th>Treatment</th>${fit.treats.map(t=>`<th>${esc(t)}</th>`).join('')}</tr></thead><tbody>${fit.treats.map((t,i)=>`<tr><th>${esc(t)}</th>${fit.treats.map((_,j)=>{if(i===j)return '<td>—</td>';const e=fit.league[j][i],v=which==='fr'?[e.est,e.est-1.959963984540054*e.se,e.est+1.959963984540054*e.se]:[e.median,e.lo,e.hi];return `<td>${v.map(x=>num(scale(r.plan.measure,x))).join(' / ')}</td>`;}).join('')}</tr>`).join('')}</tbody></table></div>`;}
function ranking(r){const fit=r.fr||r.by;if(!fit)return '';return `<div class="table-wrap"><table><caption>Treatment ranking (${r.plan.smallBetter?'lower':'higher'} values preferred)</caption><thead><tr><th>Treatment</th>${r.fr?'<th>P-score</th>':''}${r.by?'<th>SUCRA</th>':''}</tr></thead><tbody>${fit.treats.map((t,i)=>`<tr><td>${esc(t)}</td>${r.fr?'<td>'+num(r.fr.pscore[i])+'</td>':''}${r.by?'<td>'+num(r.by.sucra[i])+'</td>':''}</tr>`).join('')}</tbody></table></div><p>Rankings describe ordering uncertainty and do not establish clinical superiority or certainty of evidence.</p>`;}
function interpretation(r){const lines=[`${r.dataset.name} · ${r.dataset.timepoint}`,`The supplied data contain ${r.descriptive.studies} studies, ${r.descriptive.arms} arms and ${r.descriptive.participants} analysed participants. Counts apply to this outcome/time point and must not be summed across outcomes.`];
 for(const e of effects(r)){const nullValue=ratio(r.plan.measure)?1:0,cross=e.lower<=nullValue&&e.upper>=nullValue;lines.push(`${e.method}: ${e.treatment} versus ${e.reference}, ${r.plan.measure} ${num(e.estimate)} (${e.method==='Bayesian'?'95% credible interval':'95% confidence interval'} ${num(e.lower)} to ${num(e.upper)}). The interval ${cross?'includes':'does not include'} the null value ${nullValue}. This does not by itself establish clinical importance.`);}
 if(r.fr)lines.push(`Between-study variance τ² (DL estimate): ${num(r.fr.tau2)}; I² ${num(100*r.fr.I2)}%; Q ${num(r.fr.Q)}, df ${r.fr.df}. ${r.fr.df<=0?'Heterogeneity cannot be estimated reliably with zero residual degrees of freedom.':''} I² is descriptive; it is not an automatic GRADE downgrade.`);
 if(r.by)lines.push(`Bayesian estimates use a normal likelihood on study contrasts and finite-grid approximation for heterogeneity. They are not a binomial-likelihood analysis. Prior/grid sensitivity was not performed.`);
 const dropped=r.fr?.dropped||r.by?.dropped||[];if(dropped.length)lines.push('Excluded by the estimator: '+dropped.map(d=>d.study+' ('+d.why+')').join('; '));
 if(r.fr?.studies.some(s=>s.zero)||r.dataset.rows.some(x=>x.type==='binary'&&(x.event===0||x.event===x.n)))lines.push('Zero-cell correction was used where needed. Sparse-event findings require caution.');
 lines.push('No automatic certainty rating, causal conclusion or clinical recommendation is made. Differences in design, populations, measurement and follow-up require substantive review.');return lines.join('\n\n');
}
function methods(run){return `Analysis methods\n\nRun: ${run.id}\nCreated: ${run.at}\nEngine: ${run.version}\n\nData and analysis requirements were reviewed by AI and separately confirmed by the user. Uploaded source content and editable working data were retained separately. Blank, NR and NA were not converted to zero. Each outcome, time point, measurement unit and endpoint/change definition was analysed separately. Duplicates, invalid counts and unsupported raw correlated designs block confirmation.\n\n${run.results.map(r=>{const p=r.plan;return `${r.dataset.name} (${r.dataset.timepoint}): ${p.method}; ${p.measure}; ${p.model} effects; reference ${p.reference}; ${p.smallBetter?'lower':'higher'} values preferred. ${p.rationale||''}${r.by?' Bayesian heterogeneity prior '+p.prior+' '+(p.prior==='uniform'?p.priorMax:p.priorScale)+', draws '+p.draws+', seed '+p.seed+'.':''}`;}).join('\n\n')}\n\nFrequentist estimation: inverse-variance generalised least squares using within-study covariance for multi-arm contrasts. Generalised DerSimonian–Laird heterogeneity estimator; normal 95% confidence intervals. Common-effect analyses use zero heterogeneity in fitting. These results are not REML or Hartung–Knapp estimates.\n\nBinary measures: log RR or log OR. For a study with any empty cell, OR adds 0.5 to event/non-event cells; RR adds 0.5 to events and total according to the retained engine convention. All-zero studies provide no RR/OR information; all-event studies are excluded for OR. Exclusions are recorded. Continuous outcomes use mean difference or two-arm Hedges' g. SD is required; medians are not silently transformed.\n\nBayesian estimation, when selected: normal study-contrast likelihood, treatment effects N(0,100²), chosen heterogeneity prior. Tau is integrated on a 400-point grid (half-normal range 0 to 5 times scale, or the uniform support); conditional normal draws approximate the posterior. This is a finite-grid approximation, not exact integration or binomial sampling. The random seed is retained.\n\nNetwork assumptions: connected network, comparable treatments and outcome definitions, and plausible transitivity must be assessed. Treatment rankings do not measure evidence certainty. Automated GRADE, causal claims, baseline-risk conversion, subgroup/meta-regression and publication-bias tests are not performed.\n\nReproducibility: working-data.csv, confirmed-plan.json, audit.json, results.json, engine.js and reproduce.cjs accompany this report. Run node reproduce.cjs in the extracted export directory. Numeric outputs are generated by the statistical engine, not by a language model.\n\nReferences\nCochrane Handbook chapters 10 and 11: https://training.cochrane.org/handbook/current/chapter-10 ; https://training.cochrane.org/handbook/current/chapter-11\nnetmeta reference: https://guido-s.r-universe.dev/netmeta/doc/manual.html\nAIRepr: https://arxiv.org/abs/2502.16395\n`;
}
function body(run){return run.results.map(r=>`<article><h2>${esc(r.dataset.name)} · ${esc(r.dataset.timepoint)}</h2><p>${r.descriptive.studies} studies · ${r.descriptive.arms} arms · ${r.descriptive.participants} participants</p>${network(r)}${forest(r)}${league(r,'fr')}${league(r,'by')}${ranking(r)}<h3>Interpretation</h3><div class="document">${esc(interpretation(r))}</div></article>`).join('');}
const reportStyle='body{font:14px/1.6 Arial,sans-serif;color:#302d35;max-width:1180px;margin:24px auto;padding:20px}svg{width:100%;height:auto;max-height:550px}table{border-collapse:collapse;font-size:12px;width:100%}td,th{border:1px solid #ded7e4;padding:7px;text-align:left}th{background:#f6f0f8}.table-wrap{overflow:auto;margin:16px 0}.document{white-space:pre-wrap}article{margin:28px 0}h1,h2,h3{color:#654179}';
function html(run){return '<!doctype html><html lang="en"><meta charset="utf-8"><title>AIM-STEP analysis</title><style>'+reportStyle+'</style><h1>Analysis results</h1><p>'+esc(run.at)+'</p>'+body(run)+'<h2>Methods</h2><div class="document">'+esc(methods(run))+'</div></html>';}
function zip(files){const enc=new TextEncoder(),chunks=[],central=[];let offset=0;for(const f of files){const name=enc.encode(f.name),data=typeof f.content==='string'?enc.encode(f.content):f.content;let crc=0xffffffff;for(const byte of data){crc^=byte;for(let j=0;j<8;j++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}crc=(crc^0xffffffff)>>>0;const h=new Uint8Array(30+name.length),v=new DataView(h.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint32(14,crc,true);v.setUint32(18,data.length,true);v.setUint32(22,data.length,true);v.setUint16(26,name.length,true);h.set(name,30);chunks.push(h,data);const c=new Uint8Array(46+name.length),w=new DataView(c.buffer);w.setUint32(0,0x02014b50,true);w.setUint16(4,20,true);w.setUint16(6,20,true);w.setUint16(8,0x800,true);w.setUint32(16,crc,true);w.setUint32(20,data.length,true);w.setUint32(24,data.length,true);w.setUint16(28,name.length,true);w.setUint32(42,offset,true);c.set(name,46);central.push(c);offset+=h.length+data.length;}const end=new Uint8Array(22),v=new DataView(end.buffer);v.setUint32(0,0x06054b50,true);v.setUint16(8,files.length,true);v.setUint16(10,files.length,true);v.setUint32(12,central.reduce((n,x)=>n+x.length,0),true);v.setUint32(16,offset,true);const all=[...chunks,...central,end],out=new Uint8Array(all.reduce((n,x)=>n+x.length,0));let at=0;for(const part of all){out.set(part,at);at+=part.length;}return out;}
function docx(title,text){const ns='http://schemas.openxmlformats.org/wordprocessingml/2006/main';return zip([{name:'[Content_Types].xml',content:'<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>'},{name:'_rels/.rels',content:'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>'},{name:'word/document.xml',content:`<w:document xmlns:w="${ns}"><w:body>${[title,...text.split('\n')].map((line,i)=>`<w:p><w:pPr><w:spacing w:after="100"/></w:pPr><w:r><w:rPr>${i?'':'<w:b/>'}<w:sz w:val="${i?22:30}"/></w:rPr><w:t xml:space="preserve">${esc(line)}</w:t></w:r></w:p>`).join('')}<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1134" w:right="1134" w:bottom="1134" w:left="1134"/></w:sectPr></w:body></w:document>`}]);}
const api={esc,num,effects,network,forest,league,ranking,interpretation,methods,body,html,zip,docx};if(typeof module==='object'&&module.exports)module.exports=api;else root.AimstepAnalysisOutput=api;
})(globalThis);
