(function(root){
'use strict';
const sections=[['title','Title'],['abstract','Abstract'],['plain','Plain language summary'],['background','Background'],['objectives','Objectives'],['methods','Methods'],['results','Results'],['discussion','Discussion'],['conclusions',"Authors’ conclusions"],['declarations','Acknowledgements, author contributions and declarations'],['differences','Differences between protocol and review'],['references','References'],['supplements','Tables, figures and supplementary materials']];
const groups=[['background','objectives','methods'],['results','discussion','conclusions'],['title','abstract','plain'],['declarations','differences','supplements']];
const pick=(v,keys)=>Object.fromEntries(keys.filter(k=>v?.[k]!==undefined).map(k=>[k,v[k]]));
const brief=r=>pick(r,['uid','id','sourceNumber','title','authors','year','doi','journal','pmid','design']);
function clean(v){if(Array.isArray(v))return v.map(clean);if(!v||typeof v!=='object')return v;return Object.fromEntries(Object.entries(v).filter(([k])=>!/token|apiKey|password|secret|base64|^pdf$|^blob$|^history$|^audit$|^images$|^raw$|^snapshot$|^fullText$|^chunks$|^html$|^svg$/i.test(k)).map(([k,x])=>[k,clean(x)]));}
function projectSources(v){const out=[],add=(stage,data)=>{if(data&&Object.keys(data).length)out.push({id:'S'+(out.length+1),stage,data:clean(data)});};
 add('Protocol (plans, not evidence of completed methods)',v.protocol&&pick(v.protocol,['text','confirmedAt','updatedAt','mapping']));
 add('Eligibility criteria',v.eligibility&&{...pick(v.eligibility,['question','framework','reviewType','dateRange','language','limitsOther','confirmed']),rows:v.eligibility.activeGenerator==='machine'?v.eligibility.machineCriteria:v.eligibility.criteria,refinement:v.eligibility.activeGenerator==='machine'?v.eligibility.machineRefinement:v.eligibility.manualRefinement});
 add('Search strategy (queries are drafts unless present in executed runs)',v.search&&pick(v.search,['databases','queries','limits','modelRun','protocolSource']));
 add('Executed search runs',v.searchResults&&{runs:(v.searchResults.runs||[]).map(r=>pick(r,['id','db','query','startedAt','updatedAt','status','total','downloaded','added','exhausted','generation','notices','error']))});
 add('Title and abstract screening',v.screening&&{...pick(v.screening,['criteria','full','completedAt','sampleSize','screeningProvider','screeningCriteria','criteriaUpload','screeningStages']),pilot:pick(v.screening.pilot,['size','approved','rounds']),summary:v.screenSummary});
 add('Full-text assessment',v.fulltext&&{...pick(v.fulltext,['criteria','full','screeningProvider','screeningStages']),records:(v.fulltext.records||[]).map(brief),pilot:pick(v.fulltext.pilot,['size','approved','rounds']),summary:v.fullSummary});
 add('Extraction (only done/confirmed entries may be described as reviewed)',v.extraction&&{...pick(v.extraction,['form','studies','extractionFlow','workflow']),records:(v.extraction.records||[]).map(brief)});
 add('Risk of bias assessment',v.rob&&{...pick(v.rob,['selectedToolId','outcomes','outcomeTimepoints','outcomeMeta','studies','assess','robFlow','assessmentSetupSignature']),records:(v.rob.records||[]).map(brief)});
 const selected=v.analysis?.runs?.find(r=>r.id===v.analysis.selectedRun)||v.analysis?.runs?.at(-1);
 add('Analysis (selected saved run; stale runs must be identified)',v.analysis&&{...pick(v.analysis,['requirements','plan','manuscriptResults']),currentData:v.analysis.rows,selectedRun:selected&&pick(selected,['id','at','version','methods','interpretation'])});
 add('Certainty of evidence (real workspace only; not synthetic examples)',v.coe&&{rules:v.coe.rules,reviewer:v.coe.reviewer,real:v.coe.real,completionSummary:v.coeSummary,validationNote:'Recorded certainty values; the manuscript tool does not rerun the GRADE engine. Verify individual SoF ratings and pending rules in Certainty of evidence before publication.'});
 return out;
}
function fingerprint(v){let h=2166136261;for(const c of JSON.stringify(v)){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return(h>>>0).toString(16);}
function packets(sources,limit=8000){const out=[];for(const s of sources){const raw=JSON.stringify(s.data,null,2);for(let i=0;i<raw.length;i+=limit)out.push({id:s.id+'-'+(1+Math.floor(i/limit)),stage:s.stage,text:raw.slice(i,i+limit)});}return out;}
const str={type:'string'};
const factsSchema={type:'object',properties:{facts:{type:'array',items:{type:'object',properties:{quote:str,note:str},required:['quote','note']}},gaps:{type:'array',items:str}},required:['facts','gaps']};
function facts(value,packet){if(!Array.isArray(value?.facts)||!Array.isArray(value.gaps))throw Error('AI returned an incomplete evidence digest.');for(const f of value.facts)if(typeof f.quote!=='string'||!f.quote.trim()||!packet.text.includes(f.quote))throw Error('AI evidence quotation could not be traced to '+packet.id+'. Retry drafting.');return {...packet,facts:value.facts,gaps:value.gaps};}
function schema(ids){return {type:'object',properties:{sections:{type:'array',items:{type:'object',properties:{id:{type:'string',enum:ids},text:str,sourceIds:{type:'array',items:str}},required:['id','text','sourceIds']}},issues:{type:'array',items:str}},required:['sections','issues']};}
function validate(value,ids,sourceIds){if(!Array.isArray(value?.sections)||!Array.isArray(value.issues))throw Error('AI returned incomplete manuscript sections.');return {sections:ids.map(id=>{const found=value.sections.filter(s=>s.id===id);if(found.length!==1||typeof found[0].text!=='string'||!Array.isArray(found[0].sourceIds)||found[0].sourceIds.some(x=>!sourceIds.includes(x)))throw Error('Invalid section or source reference: '+id);return {...found[0],text:found[0].text.replace(/\s*\(sourceIds?:[^)]*\)/gi,''),label:sections.find(x=>x[0]===id)[1]};}),issues:value.issues.map(String)};}
function references(v){const unique=new Map();for(const r of [...(v.extraction?.records||[]),...(v.rob?.records||[]),...(v.fulltext?.records||[])]){const k=r.doi||r.pmid||r.uid||r.title;if(k&&!unique.has(k))unique.set(k,r);}return [...unique.values()].map(r=>[Array.isArray(r.authors)?r.authors.join(', '):r.authors,r.year,r.title,r.journal,r.doi?'DOI: '+r.doi:'',r.pmid?'PMID: '+r.pmid:''].filter(Boolean).join('. '));}
function renderText(rows){return sections.map(([id,label])=>{const row=rows.find(s=>s.id===id);return row?label+'\n'+row.text:'';}).filter(Boolean).join('\n\n');}
const auditSchema={type:'object',properties:{corrections:{type:'array',items:{type:'object',properties:{id:str,find:str,replace:str},required:['id','find','replace']}},issues:{type:'array',items:str}},required:['corrections','issues']};
function correct(rows,value){if(!Array.isArray(value?.corrections)||!Array.isArray(value.issues))throw Error('Incomplete manuscript consistency review.');const out=structuredClone(rows);for(const fix of value.corrections){const row=out.find(s=>s.id===fix.id);if(!row||typeof fix.find!=='string'||!fix.find||!row.text.includes(fix.find)||typeof fix.replace!=='string')throw Error('AI correction could not be traced to the draft.');row.text=row.text.replace(fix.find,fix.replace);}return {sections:out,issues:value.issues.map(String)};}
function wordItems(text){const labels=new Set(sections.map(x=>x[1]));const items=[];let current={label:'Manuscript',definition:''};for(const line of text.split('\n')){if(labels.has(line.trim())){if(current.definition.trim())items.push(current);current={label:line.trim(),definition:''};}else current.definition+=(current.definition?'\n':'')+line;}if(current.definition.trim())items.push(current);return items;}
const api={auditSchema,correct,wordItems,sections,groups,clean,projectSources,fingerprint,packets,factsSchema,facts,schema,validate,references,renderText};if(typeof module==='object'&&module.exports)module.exports=api;else root.AimstepManuscriptCore=api;
})(globalThis);
