const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const O=require('../app/extraction-outcomes.js'),P=require('../app/extraction-pioo.js'),B=require('../app/extraction-baseline.js');
const html=fs.readFileSync('extraction.html','utf8'),c={structuredClone,AimstepExtractionOutcomes:O,AimstepExtractionPioo:P,AimstepExtractionBaseline:B};vm.createContext(c);vm.runInContext(html.slice(html.indexOf('const FIELD_SECTIONS='),html.indexOf('let ws=null')),c);
const legacy={sections:['baseline','participant','intervention','outcome','other'],framework:'PIOO',piooVersion:1,tidierVersion:1,baselineVersion:3,fields:[{id:'legacy-custom',section:'outcome',label:'Custom result',definition:'Preserve me'},{id:'legacy-cont',section:'outcome',piooKey:'outcome.continuous',label:'Continuous data'}],outcomes:[{id:'pain',type:'continuous',name:'Pain'},{id:'response',type:'binary',name:'Response'},{id:'unknown',type:'',name:'Unknown'}],sectionArchives:{}};
c.prepareFormSections(legacy);assert.equal(legacy.framework,'PICDO');assert(!legacy.sections.includes('outcome'));assert(legacy.fields.some(f=>f.id==='legacy-custom'&&f.definition==='Preserve me'));assert.equal(legacy.fields.find(f=>f.id==='legacy-cont').section,'continuous');assert.deepEqual(legacy.outcomes.map(o=>o.id),['pain','response','unknown']);
c.removeFormSection(legacy,'continuous');assert.deepEqual(legacy.outcomes.map(o=>o.id),['response','unknown']);c.restoreFormSection(legacy,'continuous');assert(legacy.outcomes.some(o=>o.id==='pain'));assert(legacy.fields.some(f=>f.id==='legacy-cont'));legacy.fields=legacy.fields.filter(f=>f.outcomeKey!=='continuous.sd');c.prepareFormSections(legacy);assert(!legacy.fields.some(f=>f.outcomeKey==='continuous.sd'));
const removed={piooVersion:1,tidierVersion:1,baselineVersion:3,sections:[],fields:[],outcomes:[],sectionArchives:{outcome:{fields:[{id:'old-field',section:'outcome',label:'Old',definition:''}],outcomes:[{id:'b',type:'binary'},{id:'u',type:''}]}}};c.prepareFormSections(removed);assert.equal(removed.sections.length,0);assert.equal(removed.fields.length,0);c.restoreFormSection(removed,'dichotomous');assert(removed.outcomes.some(o=>o.id==='b'));assert(removed.outcomes.some(o=>o.id==='u'));assert(removed.fields.some(f=>f.id==='old-field'&&f.definition===''));
const fresh={fields:[],outcomes:[]};c.prepareFormSections(fresh);for(const section of ['continuous','dichotomous']){assert.equal(fresh.fields.filter(f=>f.section===section).length,12);assert(O.seed(section).every(f=>O.definition(f)));}assert(O.definition(O.seed('continuous').find(f=>f.outcomeKey==='continuous.sd')).includes('Never label SE'));assert(O.definition(O.seed('dichotomous').find(f=>f.outcomeKey==='dichotomous.zero')).includes('continuity'));assert.equal(O.definition({...O.seed('continuous')[0],definition:''}),'');
console.log('PASS PICDO split, 24 definitions, legacy IDs/custom rules, classified/unclassified targets, archives, independent remove/restore, intentional deletion and cleared definitions');
// Numerical review validation permits reported zero events/SD, but not fractional people.
const status=html.slice(html.indexOf('function rowCells('),html.indexOf('function statusOf('));const state={arms:[{id:'a',label:'A',n:10},{id:'b',label:'B',n:10}],nr:{},res:{o:{a:{events:0,total:10},b:{events:2,total:10}}}};const sc={ws:{form:{outcomes:[{id:'o',name:'Test',type:'binary'}]}},st:()=>state,val:x=>x??'',num:x=>x==null?null:Number(x)};vm.createContext(sc);vm.runInContext(status,sc);assert.equal(sc.missingFor('s').length,0);state.res.o.b.events=1.5;assert(sc.missingFor('s').length);sc.ws.form.outcomes[0].type='continuous';state.res.o={a:{mean:2,sd:0,n:10},b:{mean:3,sd:1,n:10}};assert.equal(sc.missingFor('s').length,0);state.res.o.b.n=2.5;assert(sc.missingFor('s').length);console.log('PASS zero events/SD, fractional participant rejection');
