const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const html=fs.readFileSync(path.join(__dirname,'../extraction.html'),'utf8');const c=vm.createContext({structuredClone});vm.runInContext(html.slice(html.indexOf('const FIELD_SECTIONS='),html.indexOf('let ws=null')),c);
const fields=[{id:'country',label:'Country'},{id:'age',label:'Mean age (years)'},{id:'n',label:'Number randomised'},{id:'therapy',label:'Background therapy'},{id:'custom',label:'My field',section:'intervention'}];const grouped=c.groupFormFields(fields);
assert.deepEqual(Array.from(grouped,f=>f.section),['baseline','participant','participant','intervention','intervention']);assert.deepEqual(Array.from(grouped,f=>f.id),fields.map(f=>f.id));assert.equal(fields[0].section,undefined);
for(const name of ['Baseline information','Participant','Intervention','Outcome','Other information'])assert(html.includes('>'+name+'</h3>'));
assert(!html.includes('id="field-chips"'));assert(!html.includes('>Study fields</h3>'));console.log('PASS: five sections, legacy field migration, IDs and custom section preservation');

const form={fields:[...fields],outcomes:[{id:'outcome1',name:'Pain'}]};c.prepareFormSections(form);assert.equal(form.sections.length,5);c.removeFormSection(form,'participant');assert(!form.fields.some(f=>f.id==='age'));assert(!form.sections.includes('participant'));c.restoreFormSection(form,'participant');assert(form.fields.some(f=>f.id==='age'));c.removeFormSection(form,'outcome');assert.equal(form.outcomes.length,0);c.restoreFormSection(form,'outcome');assert.equal(form.outcomes[0].id,'outcome1');for(const key of [...form.sections])c.removeFormSection(form,key);c.prepareFormSections(form);assert.equal(form.sections.length,0);assert.equal(form.fields.length,0);c.restoreFormSection(form,'baseline');assert(form.fields.some(f=>f.id==='country'));console.log('PASS: remove, restore, Clear persistence and retained field/outcome IDs');

const legacy={framework:'PECO',fields:[],outcomes:[]};c.prepareFormSections(legacy);assert.equal(legacy.framework,'PIOO');assert(html.includes("const FORM_FRAMEWORKS=['PIOO'];"));console.log('PASS: PIOO is the sole framework and replaces earlier selections');
