const assert=require('node:assert/strict'),R=require('../app/extraction-form-review.js'),I=require('../app/extraction-form-import.js'),L=require('../app/extraction-form-library.js');let serial=0;const id=()=>String(++serial);
function setup(form,provenance={}){const entry={id:'form',name:'Synthetic imported form',form,provenance};const updates=[];return {entry,updates,api:{find:()=>entry,id,importer:I,update:async(key,review,parsed)=>{entry.importReview=review;if(parsed)entry.form=parsed;updates.push(review);}}};}
(async()=>{
 const items=[{section:'baseline',label:'Country',definition:'',hasDefinition:false},{section:'other',label:'Duplicate',definition:'One',hasDefinition:true},{section:'other',label:'Duplicate',definition:'Two',hasDefinition:true}];const form=I.build(L.empty(),items,'replace',id,{preserveMissing:true,allowDuplicates:true});assert.equal(form.fields[0].definition,'');assert.equal(form.fields.length,3);
 const s=setup(form);s.api.model=async()=>({model:'synthetic',value:{summary:'Review the country definition.',issues:[{item:'Country',problem:'Definition is missing',suggestion:'Extract recruitment country, not affiliation country.'}],items:[]}});await R.run('form',s.api);assert.equal(s.entry.importReview.status,'complete');assert(s.entry.importReview.issues.some(x=>x.suggestion.includes('recruitment')));assert(s.entry.importReview.issues.some(x=>x.problem.includes('Duplicate')));assert.equal(s.entry.form.fields[0].definition,'');
 const enriched=setup(structuredClone(form));enriched.api.model=async()=>({model:'synthetic',value:{summary:'Supplemented',issues:[],items:[],supplements:[{id:form.fields[0].id,addition:'Extract recruitment country; NR if not reported.',reason:'Missing definition'},{id:'unknown',addition:'Ignore',reason:'Invalid id'}]}});await R.run('form',enriched.api);assert.equal(enriched.entry.form.fields[0].definition,'Extract recruitment country; NR if not reported.');assert.equal(enriched.entry.form.fields[0].definitionHistory[0].original,'');await R.run('form',enriched.api);assert.equal(enriched.entry.form.fields[0].definitionHistory.length,1);assert.equal(enriched.entry.form.fields.length,3);
 const fail=setup(form);fail.api.model=async()=>{throw Error('Offline')};await R.run('form',fail.api);assert.equal(fail.entry.importReview.status,'unavailable');assert.equal(fail.entry.form.fields.length,3);assert(fail.entry.importReview.issues.some(x=>x.problem.includes('missing')));
 const raw=setup(L.empty(),{unparsed:[{name:'raw.txt',text:'Age\nCountry\nRecruitment location.'}]});raw.api.model=async()=>({model:'synthetic',value:{summary:'Definition required.',issues:[],items:[{section:'participant',label:'Age',definition:'Invented definition'},{section:'baseline',label:'Country',definition:'Recruitment location.'},{section:'other',label:'Invented item',definition:'Invented'}]}});await R.run('form',raw.api);assert.equal(raw.entry.form.fields.length,2);assert.equal(raw.entry.form.fields[0].definition,'');assert.equal(raw.entry.form.fields[1].definition,'Recruitment location.');assert(!raw.entry.form.fields.some(f=>f.label==='Invented item'));
 const batches=R.batches(Array.from({length:45},(_,i)=>({id:i,label:'Item '+i})),[]);assert.equal(batches.length,3);assert.equal(batches.flatMap(x=>x.items).length,45);
 const local={formLibrary:[],form:L.empty(),studies:{}};L.create(local,{id:'empty',name:'Unreadable file',source:'Local import',form:L.empty(),createdAt:'2026-10-08'});assert.equal(local.formLibrary.length,1);
 console.log('PASS direct incomplete imports, no invented definitions, conflict feedback, real model adapter review, unavailable AI preserves form, grounded transcription and all-item batching');
})().catch(e=>{console.error(e);process.exitCode=1});
