// Synthetic end-to-end state tests for the AI-first full-text workflow.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const html=fs.readFileSync(path.join(__dirname,'../full-text-screening.html'),'utf8'),elements=new Map();
function el(id){if(!elements.has(id))elements.set(id,{value:'',textContent:'',innerHTML:'',hidden:false,disabled:false,style:{},dataset:{},handlers:{},parentElement:{classList:{toggle(){}}},classList:{toggle(){},add(){},remove(){}},setAttribute(){},getAttribute(){return null},querySelector(){return {textContent:'',focus(){}}},querySelectorAll(){return []},closest(){return {classList:{toggle(){}}}},addEventListener(k,f){this.handlers[k]=f},focus(){},showModal(){},close(){}});return elements.get(id);}
const ctx={console,URL,URLSearchParams,AbortController,DOMException,structuredClone,TextEncoder,Blob,Map,Set,performance,CSS:{escape:x=>x},setTimeout(){return 1},clearTimeout(){},localStorage:{getItem(){return null},setItem(){}},navigator:{},location:{href:'https://aimsetp.com/full-text-screening.html',search:'',hostname:'aimsetp.com'},document:{activeElement:null,addEventListener(){},getElementById:el,querySelectorAll(){return []},body:{dataset:{}}},window:{addEventListener(){}},confirm(){return true},AIMScreeningCriteriaDialog(){return {}},AimstepScreeningStages:require("../app/screening-stages.js"),AimstepCalibration:require('../app/screening-calibration.js')};
let code=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(m=>m[1]).find(s=>s.includes('const FT_PROMPT'));
code=code.replace(/\ninit\(\);/,`\nglobalThis.ft={setup(records){workspace=defaults();workspace.records=records;workspace.criteria={rows:[{title:'Population',condition:'Adults',uncertain:'Children'}]};workspace.criteriaSig='criteria';workspace.screeningStages={version:2,sourceSig:'criteria',elements:AimstepScreeningStages.seed(workspace.criteria)};workspace.pilot.size=3;workspace.docs=Object.fromEntries(records.map(r=>[r.uid,{kind:'pdf',hash:r.uid,source:'Synthetic PDF'}]));indexRecords();records.forEach(r=>docCache.set(r.uid,{uid:r.uid,fullText:r.abstract,chunks:[{id:'C1',text:r.abstract}],evidence:{method:'synthetic',byCriterion:{Population:[{id:'C1',score:1}]}}}));pilotView=-1;pilotReviewDrafts.clear();pilotReviewErrors.clear();expandedPilotAssessments.clear();fullFilter='';},get:()=>workspace,replace(w){workspace=w;indexRecords()},view(i){pilotView=i},bindSave(fn){save=fn},bindRead(fn){readReport=fn;resolvePilotModel=async()=>({name:'synthetic',provider:'typesafe'})},stub(){render=()=>{renderPilot();renderFull()};publishSummary=()=>{};log=()=>{};showNotice=()=>{};toast=()=>{};updateExportCount=()=>{}},startPilotRound,savePilotReview,beginPilotMistake,approvePilot,approvalsValid,roundState,pilotMetrics,currentCalibration,validPilotReview,pilotReviewSignature,pilotReviewDrafts,pilotReviewErrors,renderPilot,renderFull,reportCard,fullCategoryIds,fullDecide,fullReviewErrors,runFull,finalOf,summary,ftPrompt,ftDecision,reasonDrafts,screeningStageSig};`);
vm.runInNewContext(code,ctx);const t=ctx.ft;t.stub();
const records=Array.from({length:9},(_,i)=>({uid:'r'+i,title:'Synthetic study '+i,abstract:'Adults and children participated.',authors:['Synthetic Reviewer'],year:'2026',journal:'Synthetic'}));
const currentRoundHTML=()=>el('rounds').innerHTML.match(/<button[^>]*class="round current[^"]*"[^>]*>(.*?)<\/button>/)?.[1]||'';
const names=['include','unclear','exclude','conflicts','check'],buttons=names.map(key=>({dataset:{fullCategory:key},attrs:{},setAttribute(k,v){this.attrs[k]=v}}));el('full-categories').querySelectorAll=()=>buttons;
let saved,calls=[];t.setup(records);t.bindSave(async()=>{saved=structuredClone(t.get())});
t.bindRead(async(id,round,signal,variant=1)=>{const w=t.get(),bundle=w.pilot.rounds[round]?.calibration||w.pilot.approved?.calibration;calls.push({id,round,variant,bundle:structuredClone(bundle)});return {decision:'unclear',round,model:'synthetic',criteriaSig:'criteria',stageSig:t.screeningStageSig(),documentHash:id,calibrationHash:bundle?.hash,prompt:'fulltext-v2-calibrated',promptHash:id+round,at:id+round,criteria:[{dimension:'Population',judgment:'unclear',quote:'',known:true,reason:'Age eligibility unclear'}]}});
(async()=>{
 await t.startPilotRound();let w=t.get(),st=t.roundState(0),ids=st.ids;assert.equal(st.aiDone,true);assert.equal(st.votesDone,false);
 const card=t.reportCard(ids[0],{attr:'pvote'});assert(card.includes('AI decision: Include'));assert(card.includes('data-review="agree"'));assert(card.includes('data-review="mistake"'));assert(card.includes('Open full text'));assert(!card.includes('data-pvote'));assert(!card.includes('stays hidden'));
 await t.startPilotRound();assert.equal(w.pilot.rounds.length,1);assert(!currentRoundHTML().includes('AI accuracy'));
 await t.savePilotReview(ids[0],'agree');await t.savePilotReview(ids[1],'agree');t.beginPilotMistake(ids[2]);await t.savePilotReview(ids[2],'mistake');assert(!w.pilot.human[ids[2]]);assert.match(t.pilotReviewErrors.get(ids[2]),/Explain why/);
 t.pilotReviewDrafts.get(ids[2]).note='Children are not eligible under Population.';
 const before=JSON.stringify(w);t.bindSave(async()=>{throw Error('Synthetic disk failure')});await t.savePilotReview(ids[2],'mistake');assert.equal(JSON.stringify(w),before);assert.match(t.pilotReviewErrors.get(ids[2]),/Please retry/);assert(t.pilotReviewDrafts.has(ids[2]));
 t.bindSave(async()=>{saved=structuredClone(t.get())});await t.savePilotReview(ids[2],'mistake');assert.equal(w.pilot.human[ids[2]].decision,'exclude');assert.match(w.pilot.human[ids[2]].reason,/Children/);assert(t.roundState(0).revealed);assert.equal(t.pilotMetrics(ids).accuracy,2/3);assert(currentRoundHTML().includes('AI accuracy 67%'));assert(currentRoundHTML().includes('Round 1 Reviewed'));
 assert.equal(el('pilot-agreed-count').textContent,2);assert.equal(el('pilot-mistake-count').textContent,1);
 for(const [filter,id] of [['agreed',ids[0]],['differ',ids[2]]]){el('pilot-filter').handlers.click({target:{closest:()=>({dataset:{filter}})}});assert(el('pilot-list').innerHTML.includes(records.find(r=>r.uid===id).title));}
 for(const id of [ids[0],ids[2]]){const initial=t.reportCard(id,{attr:'pvote'});assert(initial.includes('data-assessment hidden'));assert(initial.includes(id===ids[0]?'Agreed':'Corrected'));const body={hidden:true},attrs={},toggle={dataset:{toggleAssessment:id},closest:()=>({querySelector:()=>body}),setAttribute:(k,v)=>attrs[k]=v};el('pilot-list').handlers.click({target:{closest:sel=>sel==='[data-toggle-assessment]'?toggle:null}});assert.equal(body.hidden,false);assert.equal(attrs['aria-expanded'],'true');assert(!t.reportCard(id,{attr:'pvote'}).includes('data-assessment hidden'));}
 const bundle=t.currentCalibration();assert.equal(bundle.pending.length,0);assert.equal(bundle.lessons.length,3);assert.equal(bundle.lessons.filter(l=>l.review==='agree').length,2);assert(bundle.lessons.some(l=>l.review==='mistake'&&l.exclusionReason.includes('Children')));
 t.beginPilotMistake(ids[0]);assert(!currentRoundHTML().includes('AI accuracy'));await t.approvePilot();assert(!t.approvalsValid());await t.startPilotRound();assert.equal(w.pilot.rounds.length,1);await t.savePilotReview(ids[0],'agree');
 t.bindSave(async()=>{throw Error('Synthetic approval save failure')});await assert.rejects(()=>t.approvePilot(),/approval save failure/);assert(!t.approvalsValid());t.bindSave(async()=>{saved=structuredClone(t.get())});
 await t.approvePilot();assert(t.approvalsValid());t.replace(structuredClone(saved));w=t.get();assert(t.approvalsValid(),'Approval survives reload with unchanged PDF');
 const oldHash=w.docs[ids[0]].hash;w.docs[ids[0]].hash='changed';assert(!t.approvalsValid());w.docs[ids[0]].hash=oldHash;
 const oldReview=structuredClone(w.pilot.human[ids[0]]);delete w.pilot.human[ids[0]].reviewMode;assert(!t.validPilotReview(ids[0],0));assert(!t.approvalsValid());w.pilot.human[ids[0]]=oldReview;
 await t.startPilotRound();assert.equal(w.pilot.rounds.length,2);assert.equal(w.pilot.approved,null);assert(calls.slice(3).every(c=>c.bundle.lessons.length===3));const second=t.roundState(1).ids;assert(second.every(id=>!ids.includes(id)));
 for(const id of second)await t.savePilotReview(id,'agree');await t.approvePilot();assert(t.approvalsValid());
 const prompt=JSON.parse(t.ftPrompt(records[0],{chunks:[{id:'C1',text:records[0].abstract}],evidence:{byCriterion:{Population:[{id:'C1'}]}}},2,1,w.pilot.approved.calibration));assert.equal(prompt.reviewerCalibration.totalLessons,6);assert(prompt.reviewerCalibration.examples.some(e=>e.review==='mistake'));
 await t.runFull();assert.equal(calls.filter(c=>c.round===2).length,6,'Two formal readings for each remaining report');assert(calls.filter(c=>c.round===2).every(c=>c.bundle.lessons.length===6));
 const remaining=records.map(r=>r.uid).filter(id=>!ids.includes(id)&&!second.includes(id));assert.equal(t.summary().unclear,3);assert.equal(t.summary().completed,false);
 assert.equal(el('check-list').hidden,true);for(const key of names){const button=buttons.find(b=>b.dataset.fullCategory===key);el('full-categories').handlers.click({target:{closest:()=>button}});assert.equal(el('check-list').hidden,false);assert.equal(button.attrs['aria-pressed'],'true');if(t.fullCategoryIds(key).length){assert(el('check-list').innerHTML.includes('data-fvote="include"'));assert(el('check-list').innerHTML.includes('data-fvote="exclude"'));assert(!el('check-list').innerHTML.includes('data-fvote="unclear"'));}el('full-categories').handlers.click({target:{closest:()=>button}});assert.equal(el('check-list').hidden,true);}
 assert(t.reportCard(ids[0],{attr:'fvote'}).includes('#'+w.sourceNumbers.byUid['uid:'+ids[0]]+' · Synthetic 2026'));
 assert(t.fullCategoryIds('include').includes(ids[0]));assert(t.fullCategoryIds('exclude').includes(ids[2]));assert(t.fullCategoryIds('unclear').includes(remaining[0]));assert.deepEqual(Array.from(t.fullCategoryIds('check')),remaining);
 const rid=remaining[0];await t.fullDecide(rid,'exclude');assert(!w.full.human[rid]);assert.match(t.fullReviewErrors.get(rid),/exclusion reason/);t.reasonDrafts.set('fvote|'+rid,'Population: children');t.bindSave(async()=>{throw Error('Synthetic failure')});await t.fullDecide(rid,'exclude');assert(!w.full.human[rid]);assert.match(t.fullReviewErrors.get(rid),/Please retry/);
 t.bindSave(async()=>{saved=structuredClone(t.get())});await t.fullDecide(rid,'exclude');assert.equal(t.finalOf(rid).decision,'exclude');assert(t.fullCategoryIds('exclude').includes(rid));await t.fullDecide(rid,'include');assert.equal(w.full.human[rid].reason,'');
 for(const id of remaining.slice(1))await t.fullDecide(id,'include');assert(t.summary().completed);assert.equal(t.summary().humanChecked,3);
 // Criterion conflict is separate from Check, and incomplete readings never appear as Maybe.
 const conflict=remaining[1];delete w.full.human[conflict];w.full.ai[conflict].criteria=[{dimension:'Population',known:true,judgment:'not met',quote:'children',passage:'C1'}];w.full.ai2[conflict].criteria=[{dimension:'Population',known:true,judgment:'met'}];assert(t.fullCategoryIds('conflicts').includes(conflict));assert(!t.fullCategoryIds('check').includes(conflict));assert(!t.summary().completed);await t.fullDecide(conflict,'include');assert(t.summary().completed);
 delete w.full.human[remaining[2]];delete w.full.ai2[remaining[2]];assert(!t.fullCategoryIds('unclear').includes(remaining[2]));assert(!t.summary().completed);
 assert.equal(el('full-feed-wrap').hidden,true);assert.equal(el('full-now').hidden,true);assert(html.includes('id="full-progress" hidden'));assert(!html.includes('id="check-scope"'));assert(!html.includes('id="pilot-voted"'));
 const known=[...html.slice(0,html.indexOf('<script src="app/screening-calibration')).matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(known).size,known.length,'Unique HTML IDs');for(const id of elements.keys())assert(known.includes(id),'Missing UI binding '+id);
 t.setup(records);const edited=t.get();edited.screeningStages.elements[0].inclusion='Synthetic edited population';
 assert.equal(JSON.parse(t.ftPrompt(records[0],{chunks:[],evidence:{byCriterion:{}}},0)).criteria[0].inclusionRule,'Synthetic edited population');
 const judged=t.ftDecision({decision:'exclude',reason:'Deleted criterion',criteria:[{dimension:'Removed element',judgment:'not met',quote:'Adults',passage:'C1'},{dimension:'Population',judgment:'met'}]},{chunks:[{id:'C1',text:'Adults'}]});
 assert.equal(judged.decision,'include');assert.equal(judged.criteria.length,1);assert.equal(judged.reason,'');
 console.log('PASS: edited full-text criteria reach the prompt; deleted elements cannot exclude reports');
 console.log('PASS: full-text AI-first review, accuracy, drafts, rollback/retry, legacy and document validity, approval/reload, calibrated next round and formal passes, categories, binary review and completion');
})().catch(e=>{console.error(e);process.exitCode=1});
