const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),P=require('../app/extraction-pioo.js');
const fields=P.seed('intervention');assert.equal(fields.length,13);assert.equal(fields[0].label,'Number of arm');assert(fields.every(f=>!/^\d/.test(f.label)&&!/[—–-]/.test(f.label)));
const form={piooVersion:1,tidierVersion:1,sections:['intervention'],fields:[...fields.slice(1),{id:'extra',section:'intervention',label:'Comparator'}],sectionArchives:{}};P.migrate(form);assert.equal(form.fields.length,13);assert(!form.fields.some(f=>f.id==='extra'));assert.equal(form.removedInterventionFields[0].id,'extra');P.migrate(form);assert.equal(form.fields.length,13);
const items=fields.filter(P.isArmItem),arms=Array.from({length:10},(_,i)=>({label:i===9?'Control':'Treatment '+(i+1),dose:'',randomised:'20',items:items.map(f=>({id:f.id,value:f.label+' for arm '+(i+1),passage:'C1',quote:'evidence'}))}));
P.validateArmItems({fields:[{id:fields[0].id,value:'10'}],arms},fields);
assert.throws(()=>P.validateArmItems({fields:[{id:fields[0].id,value:'11'}],arms},fields),/count/);
assert.throws(()=>P.validateArmItems({arms:[{label:'Control',items:[]}]},fields),/incomplete/);
assert.throws(()=>P.validateArmItems({arms:[arms[0],arms[0]]},fields),/duplicated/);
const html=fs.readFileSync('extraction.html','utf8'),code=html.slice(html.indexOf('function applyDraft('),html.indexOf('async function runAI('));let seq=0;const state={fields:{},arms:[],res:{},tp:{}};const c={AimstepExtractionPioo:P,st:()=>state,ws:{form:{fields,outcomes:[]}},text:(v,n)=>String(v??'').slice(0,n),val:c=>c?.v||'',squash:s=>String(s??'').trim().toLowerCase(),cell:(v,src,extra)=>({v,src,...extra}),uid8:()=>String(++seq)};vm.createContext(c);vm.runInContext(code,c);const draft={value:{fields:[],arms,results:[]},verify:()=> 'evidence'};c.applyDraft('synthetic',draft);assert.equal(state.arms.length,10);assert.equal(state.arms[9].label.v,'Control');assert.equal(Object.keys(state.arms[9].items).length,12);state.arms[0].items[items[0].id]={v:'Human correction',src:'human'};c.applyDraft('synthetic',draft);assert.equal(state.arms.length,10);assert.equal(state.arms[0].items[items[0].id].v,'Human correction');assert.equal(state.arms[9].items[items[1].id].quote,'evidence');console.log('PASS 13 clean fields, extra removal, per-arm completeness/count checks, ten arms including control, ordered storage and preserved human edits');
// The existing study reviewer renders one complete TIDieR group per arm, in order.
const nodes={};Object.assign(c,{current:'synthetic',recBy:()=>({uid:'synthetic',title:'Synthetic study'}),studyLabel:()=> 'Synthetic study',esc:x=>String(x??''),$:id=>nodes[id]??={},inp:(v,attrs)=>`<input ${attrs} value="${v?.v||''}">`,rowCheck:()=>'',unverified:()=>0,missingFor:()=>[]});vm.runInContext(html.slice(html.indexOf('function renderStudy(){'),html.indexOf('function rowCheck(')),c);c.renderStudy();assert.equal((nodes['study-body'].innerHTML.match(/data-arm-item=/g)||[]).length,120);assert(nodes['study-body'].innerHTML.indexOf('Arm 1 · Treatment 1')<nodes['study-body'].innerHTML.indexOf('Arm 10 · Control'));console.log('PASS ten sequential reviewer groups with 12 editable items each');
