const assert=require('node:assert/strict'),I=require('../app/extraction-form-import.js'),B=require('../app/extraction-baseline.js'),P=require('../app/extraction-pioo.js'),O=require('../app/extraction-outcomes.js');
const rows=I.csv('Section,Item,Definition\r\nParticipant,Age,"Mean age, in years\nNR if missing"\r\n');const items=I.table(rows,'Form');assert.equal(items[0].section,'participant');assert.equal(items[0].definition,'Mean age, in years\nNR if missing');assert.throws(()=>I.csv('"unfinished'),/unclosed/);
const template=I.table([['Item'],['Country'],['Author']],'Baseline information');assert.equal(template[0].hasDefinition,false);const definitions=I.table([['Item','Definition'],['Country','Use recruitment country']],'Baseline information');const merged=I.dedupe([...template,...definitions]);assert.equal(merged[0].definition,'Use recruitment country');assert.throws(()=>I.dedupe([...definitions,{...definitions[0],definition:'Other rule'}]),/Conflicting/);
let id=0;const old={sections:['baseline','other'],fields:[{id:'country',section:'baseline',label:'Country',definition:'Old'},{id:'keep',section:'other',label:'Keep',definition:'Custom'}],outcomes:[{id:'o',name:'Pain'}],sectionArchives:{}};
const add=I.build(old,merged,'merge',()=>String(++id));assert.equal(add.fields.find(f=>f.label==='Country').id,'country');assert.equal(add.fields.find(f=>f.label==='Country').definition,'Use recruitment country');assert(add.fields.some(f=>f.id==='keep'));assert.equal(old.fields[0].definition,'Old');
const replaced=I.build(old,[{section:'intervention',label:'Custom treatment item',definition:'Custom evidence rule',hasDefinition:true}],'replace',()=>String(++id));assert.equal(replaced.fields.length,1);assert.equal(replaced.outcomes.length,0);B.migrate(replaced);P.migrate(replaced);O.migrate(replaced);P.clearOtherDefaults(replaced);assert.equal(replaced.fields.length,1);assert.equal(replaced.fields[0].definition,'Custom evidence rule');assert(P.isArmItem(replaced.fields[0]));assert.throws(()=>I.build(old,[],'replace',()=>''),/at least/);
(async()=>{const file=new File(['[{"section":"Participant","item":"Age","definition":"Extract age"}]'],'form.json');assert.equal((await I.read(file))[0].definition,'Extract age');await assert.rejects(I.read(new File(['bad'],'form.xls')),/Use .xlsx/);console.log('PASS CSV quoting/multiline, section mapping, separate definitions, conflict detection, stable IDs, merge/replace, custom items survive migrations, JSON and invalid formats');})().catch(e=>{console.error(e);process.exitCode=1});
// Imported custom fields and definitions reach the actual model request, shared by pilot and main.
const fs=require('node:fs'),vm=require('node:vm'),R=require('../app/extraction-results.js'),html=fs.readFileSync('extraction.html','utf8');let captured;
const context={AimstepExtractionPioo:P,AimstepExtractionResults:R,ws:{form:replaced},recBy:()=>({title:'Synthetic import trial'}),loadDoc:async()=>({chunks:[{id:'C1',text:'Synthetic arm evidence',section:'Methods'}]}),itemDefinition:f=>f.definition,fieldSection:f=>f.section,embedTexts:async()=>{throw Error('No network in test')},keywordScores:()=>[1],text:(s,n)=>String(s??'').slice(0,n),squash:s=>String(s).toLowerCase(),fingerprint:()=>'',now:()=>'',pilotModelJSON:async messages=>{captured=JSON.parse(messages[1].content);return {value:{fields:[],arms:[{label:'Control',items:[{id:replaced.fields[0].id,value:'NR'}]}],results:[]},model:'synthetic'};}};
vm.createContext(context);vm.runInContext(html.slice(html.indexOf('const EXT_PROMPT='),html.indexOf('// Merge an AI draft')),context);
context.aiExtract('synthetic').then(d=>{assert.equal(captured.form.interventionItems.length,1);assert.equal(captured.form.interventionItems[0].definition,'Custom evidence rule');assert.equal(captured.form.interventionItems[0].label,'Custom treatment item');assert.equal(d.value.arms[0].items[0].value,'NR');console.log('PASS imported custom items and definitions feed actual shared AI prompt and normalized results');}).catch(e=>{console.error(e);process.exitCode=1});
