const assert=require('node:assert/strict'),S=require('../app/rob-outcome-sources.js'),I=require('../app/extraction-form-import.js');
const form={outcomes:[{id:'pain',name:'Pain',timepoint:'12 weeks'}],fields:[]};
assert.deepEqual(S.extractionSources({form,studies:{}}),[]);
const sources=S.extractionSources({form,studies:{a:{ai:{rawResults:[{outcome:'pain',timepoint:'24 weeks',mean:2}]}}}});assert(sources[0].text.includes('24 weeks'));assert(!sources[0].text.includes('12 weeks'));
const rows=S.parse('Outcome,Time point\nPain,12 weeks\nFatigue,\nPain,24 weeks','csv',I.csv);assert.equal(rows.length,3);assert(S.issues(rows[1]).includes('missing'));assert.equal(S.normalize([...rows,rows[0]]).length,3);
assert.equal(S.parse(JSON.stringify([{sheet:'Results',rows:[['Outcome','Time point'],['Pain','6 weeks']]}]),'xlsx',I.csv)[0].timepoint,'6 weeks');
(async()=>{const signal=new AbortController().signal;const extracted=await S.extract([{name:'test',text:'Pain at 12 weeks. Fatigue.'}],async()=>({model:'synthetic',value:{outcomes:[{outcome:'Pain',timepoint:'12 weeks',issue:''},{outcome:'Fatigue',timepoint:'99 weeks',issue:''},{outcome:'Invented',timepoint:'12 weeks',issue:''}]}}),signal);assert.equal(extracted.length,2);assert.equal(extracted[1].timepoint,'');const notes=await S.check(rows,async()=>({value:{issues:[{index:0,message:'Specify the pain measure.'},{index:99,message:'Ignore'}]}}),signal);assert.equal(notes.length,3);assert(notes[0].includes('pain measure'));assert(notes[1].includes('missing'));console.log('PASS actual extraction only, explicit time points, CSV/XLSX parsing, missing-value feedback, deduplication, grounded AI intake and scoped check feedback');})().catch(e=>{console.error(e);process.exitCode=1});

const corrected=S.extractionSources({form,studies:{a:{tp:{pain:{v:'6 weeks'}},ai:{rawTimepoints:{pain:'24 weeks'},rawResults:[{outcome:'pain',timepoint:'24 weeks',arm:'A'}]}}}});assert(corrected[0].text.includes('6 weeks'));assert(!corrected[0].text.includes('24 weeks'));
